### ISSUE TITLE
screen height discrepancies

### ISSUE THREAD

**Issue by KakCAT** [Kosmonaut3d/DeferredEngine#2]
I'm trying to fully understand the deferred engine to create another one  similar but quite toned down for a game.

It seems there are some discrepancies between the height at GameSettings (720) which is used to create all render targets, and the height used in some shaders (i.e. SSAO, using 800). Is this intended (to create some kind of effect to blur the RT when blitting afterwards) or SSAO should be supposed to use the same resolution?

Thanks.

**Comment by Kosmonaut3d** [comment]
fixed with 
https://github.com/Kosmonaut3d/DeferredEngine/commit/f772b53e7e09dde6d0dd0682f4c4c1f1f6957b69
